package com.example.spellbook5eapplication.app.viewmodel

enum class OverlayType {
    LARGE_SPELLCARD,
    DELETE_PROMPT,
    ERASE_PROMPT,
    SETTINGS,
    PROFILE,
    ADD_TO_SPELLBOOK,
    FILTER,
    MAKE_SPELL,
    QUICKPLAY_SPELLBOOK,
    LARGE_QUICKSPELLCARD,
    CREATE_SPELLBOOK,
    REMOVE_SPELLBOOK,
    REMOVE_SPELL_FROM_SPELLBOOK,
    EDIT_SPELL,
    SHARE_TOKEN
}